---
- hosts: all
  roles:
    - role: node
      tags:
        - node
    - role: common
      tags:
        - common
    - role: kubernetes
      tags:
        - kubernetes
    - role: infra
      tags:
        - infra
