- ansible.builtin.import_role:
    name: geerlingguy.homebrew
  vars:
    homebrew_cask_apps:
      - visual-studio-code
      - iterm2
      - spectacle
    homebrew_installed_packages:
      - direnv
      - asdf
      - watch
      - tree
      - go
      - jq
      - pre-commit
      - gawk
      - coreutils
      - yq
      - fzf
- name: "Add python bin to profile"
  lineinfile:
    path: ~/.profile
    line: "export PATH=$PATH:~/Library/Python/3.8/bin"
    state: present
    backup: yes
- name: "Add direnv to profile"
  lineinfile:
    path: ~/.profile
    line: 'eval "$(direnv hook zsh)"'
    backup: yes
- name: "Hook asdf"
  lineinfile:
    path: ~/.profile
    line: ". $(brew --prefix asdf)/libexec/asdf.sh"
    backup: yes
- name: Configure Specatacle
  ansible.builtin.copy:
    src: SpectacleShortcuts.json
    dest: "~/Library/Application Support/Spectacle/Shortcuts.json"

- name: git-tasks
  ansible.builtin.include_tasks: git.yaml
- name: shell-tasks
  ansible.builtin.include_tasks: shell.yaml
